### ISSUE TITLE
MacOS Error 

### ISSUE THREAD

**Issue by CyberMad41** [GSA/FedRAMP-OllaLab-Lean#9]
Hello amazing TTS 
I'm getting this error on MacOS during installation: 

`  [ 6/26] Cythonizing statsmodels/tsa/exponential_smoothing/_ets_smooth.pyx
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1lqecrs6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1lqecrs6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-1lqecrs6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-1lqecrs6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 344, in <module>
        File "/tmp/pip-build-env-1lqecrs6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-1lqecrs6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: statsmodels/tsa/exponential_smoothing/_ets_smooth.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Error: building at STEP "RUN pip install --no-cache-dir -r requirements.txt": while running runtime: exit status 1`

on Mac: 
brew install openblas gfortran pkg-config
pip3 install --upgrade pip setuptools wheel
pip3 install numpy
pip3 install --upgrade cython

I tried to troubleshoot it without any success any advice ?

**Comment by Cybonto** [comment]
Do you use Docker / Docker Desktop or Podman / Podman Desktop?

**Comment by Cybonto** [comment]
@CyberMad41 : I was able to replicate similar error on my Mac. It was one or more packages in the requirements.txt files that caused the error on Mac. You would need to trace the error message back to which package, remove the package from the requirements.txt files (there is one for [jupyter_lab](https://github.com/GSA/FedRAMP-OllaLab-Lean/tree/main/jupyter_lab) and one for [streamlit_app](https://github.com/GSA/FedRAMP-OllaLab-Lean/tree/main/streamlit_app)). In my case, I need to remove sentence-transformers, autogluon, gensim, cryptography and spacy. Those packages can be installed later via logging into the instance shell cli.

**Comment by CyberMad41** [comment]
I'm using podman and I will test it with these suggestions. Thanks a lot.
